name: Publish to NPM

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.0

      - name: Build NPM package
        run: deno task build:npm

      - name: Publish to NPM
        run: |
          cd npm
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
